### ISSUE TITLE
How to delete entity

### ISSUE THREAD

**Issue by kevbob1** [zilverline/sequent#104]
I am using this project to teach myself CQRS/ Event Sourcing.   I am trying to implement a Delete command and Event for one of aggregates.  I don't see an example of how to do this in the specs or example rails app.  What is the recommended way on how to implement this feature?

**Comment by lvonk** [comment]
Hi @kevbob1 

You could implement this as follows:

```ruby
# the command
class DeleteAccount < Sequent::Core::Command
end

# events
class AccountDeleted < Sequent::Core::Event
end

# aggregate root
class Account < Sequent::Core::AggregateRoot
  def delete
    apply AccountDeleted
  end
end

# command handler
class AccountCommandHandler < Sequent::Core::BaseCommandHandler
  on DeleteAccount do |command|
    account = repository.load_aggregate(command.aggregate_id, Account)
    account.delete
  end
end
```

Hope this helps.
