### ISSUE TITLE
Sagas？

### ISSUE THREAD

**Issue by pinyin** [zilverline/sequent#11]
Hi,

I'm also interested in implementing CQRS/ES in Ruby and searched into this repo.

May I ask how would you support sagas/process managers? Because I didn't notice any related codes.

**Comment by lvonk** [comment]
Hi,

This is indeed not in Sequent. Currently we implemented this in our own application using an EventHandler that executes new Commands. You could do this in the same transaction, but also choose to do this in the background with for instance delayed job.

Hope this helps.
