### ISSUE TITLE
Custom validation ?

### ISSUE THREAD

**Issue by checkraiser** [zilverline/sequent#113]
How to use custom validation to talk to external service to check validation in Command ?

**Comment by lvonk** [comment]
Hi @checkraiser 

A command uses `ActiveModel::Validations`, so you have the same hooks and possibilities to create custom validations e.g.

```ruby
class CreateInvoice < Sequent::Core::Command
  attrs vat: String
  validate :vat_valid, if: {vat.present?}

  def vat_valid
    valid_vat = ExternalApi.validate(vat)
    errors.add(:vat, :invalid) unless valid_vat
  end
end
```
You could also choose to implement this kind of validation in a `CommandHandler` and raise an exception when validation fails.

Hope this helps
