### ISSUE TITLE
Uniqueness constraints

### ISSUE THREAD

**Issue by checkraiser** [zilverline/sequent#114]
What's the best way to validate uniqueness constraints of an attribute in Domain ?

**Comment by lvonk** [comment]
Hi @checkraiser,

If an attribute has to be unique across aggregates (like e.g. usernames) you can introduce a `Usernames` aggregate that ensure uniques. The `unique` constraint on `aggregate_id` and `sequence_number` plus your domain logic checking for uniqueness is then enough.

E.g. s simple aggregate given out usernames can be like this:

```ruby
class Usernames < Sequent::Core::AggregateRoot
  # rest of class omitted...

  def add_username(username)
    fail "Username already taken" if @usernames.include?(username)
    apply UsernameAdded, username: username
  end

  on UsernameAdded do |event|
    @usernames ||= Set.new
    @usernames << event.username
  end
end
```

Hope this helps.

PS. We are working on sequent 3.0 and re-writing the docs. Please checkout https://github.com/zilverline/sequent/pull/110 since it contains lots of new features and better documentation (work in progress)

**Comment by checkraiser** [comment]
Hi @Ivonk, thanks for the answer. Where could i learn more about `AggregateRoot` ?

**Comment by lvonk** [comment]
There is lot's of information on the internet. Google for Domain Driven Design. 

There is a small PDF from Eric Evans https://domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf that gives a good overview of DDD. 

Also the README in sequent gives some information on the  building blocks in Sequent.

**Comment by checkraiser** [comment]
@lvonk As i understand, for the above example, we have to create another `Organization` AggregateRoot to manage collection of `usernames`, and it'll handle the command `addAccount` to validate uniqueness.
```
class Organization < AggregateRoot
   attrs :usernames, Array
end
```
class Account < Organization
   attrs :username
end
```
Am i right ?

**Comment by lvonk** [comment]
Hi @checkraiser,

Almost there, in your case both `Account` and `Organization` will be an `AggregateRoot`. Ps No need to override the methods `build_event` or `load_from_history`.


For instance:
```ruby

class Organization < Sequent::Core::AggregateRoot
  def initialize(id)
    super(id)
    apply OrganizationCreated
  end

  def add_account(username)
     # Perhaps you should do this check regardless of case (upcase/downcase). Depends on your domain.
     fail "Username already taken" if @usernames.include?(username)
     apply AccountAddedToOrganization, username: username
  end

  on AccountAddedToOrganization do |event|
    @usernames ||= Set.new
    @usernames << event.username
  end
end

class OrganizationCommandHandler < Sequent::Core::BaseCommandHandler
  on AddAccount do |command|
      do_with_aggregate(command, Organization) do |organization|
         organization.add_account(command.username)
         repository.add_aggregate Account.new(Sequent.new_uuid, command.username, organization.aggregate_id)
      end
  end
end

class Account < Organization
  def initialize(id, username, organization_id)
    super(id)
    apply AccountCreated
  end
  
  on AccountCreated do |event|
    @organization_id = event.organization_id
    @username = event.username
  end
end
```

So two things to note:

1) You implement your domain logic (like checking for existence of usernames) in your methods. 
2) You set the new state in the event handler in you domain class, the `on` blocks. Not in your methods.

```ruby
# WRONG
def set_name(name)
  @name = name
  apply NameSet, name: name
end

# CORRECT
def set_name(name)
  apply NameSet, name: name
end

on NameSet do |event|
  @name = event.name
end
```

Hopes this helps.
