### ISSUE TITLE
Test DB not created

### ISSUE THREAD

**Issue by mattgibson** [zilverline/sequent#128]
After following the steps in Getting Started, the final step `bundle exec rspec` fails with the following error:

```
  FATAL:  database "projectname_test" does not exist
```
It's not clear how to create the test DB from the docs.

**Comment by mattgibson** [comment]
`RACK_ENV=test bundle exec rake sequent:db:create` for anyone googling :)

**Comment by lvonk** [comment]
Thanks for reporting!
