### ISSUE TITLE
Heroku deployment 

### ISSUE THREAD

**Issue by revskill10** [zilverline/sequent#132]
When deploying to Heroku, i've got problem with migration.
Heroku postgres doesn't allow us create database, so what's command should i use to migrate event_store to existing database ?

**Comment by lvonk** [comment]
Hi,

Hmm there is no separate rake task for this (yet). Until this task is in sequent you can try to create your own rake task which does the following:

```ruby
  sequent_schema = File.join(Sequent.configuration.database_config_directory, "#{Sequent.configuration.event_store_schema_name}.rb")

  fail "File #{sequent_schema} does not exist. Check your Sequent configuration." unless File.exists?(sequent_schema)

  db_config = Sequent::Support::Database.read_config(ENV['RACK_ENV'])
  Sequent::Support::Database.establish_connection(db_config)
  Sequent::Support::Database.create_schema(Sequent.configuration.event_store_schema_name)
  load(sequent_schema)
```

This will create the sequent schema as you specified in the sequent config in your own database.

**Comment by revskill10** [comment]
@lvonk Do you want a PR for this ? I'll test first then submit PR

**Comment by lvonk** [comment]
Hi @revskill10 that would be nice. See https://github.com/zilverline/sequent/blob/master/lib/sequent/rake/migration_tasks.rb

Suggestion: `sequent:db:sequent_schema:create` as taks name

**Comment by lvonk** [comment]
This is now fixed by https://github.com/zilverline/sequent/pull/138
