### ISSUE TITLE
Hi. Thanks for a great framework! Sequent looks to be very useful for us.

### ISSUE THREAD

**Issue by lvonk** [zilverline/sequent#136]
Hi. Thanks for a great framework! Sequent looks to be very useful for us.

I've been starting to learn how to use it, but have found that some things in the docs are a little unclear, making it slow to get started. I've kept track of the questions that I've had in mind whilst going along, so perhaps it would be helpful when revising the docs for me to post them here:

- Is it better to have the attributes (e.g. the `title` of the `Post`) as fields on the command/event or to have a `PostAttributes` value object to encapsulate them so that the command/event has that as a single attribute instead? What are the pros and cons of each approach?
- How and when are the events applied when the aggregate is reconstructed from the event stream? The `initialize` method will be called each time a new object is instantiated, but there is logic in the examples that looks like it should only run when the initial `AddPost` command is handled.
- What does an `UpdatePost` command/event look like if I am using a HTML form to do the update (many fields)
- Why are `AggregateRoot`s and `Projector`s different classes? I know that this is the point of the CQRS pattern, but the docs and examples show no use case where the projectors do anything other than a 1-1 mapping of `Projector` to `AggregateRoot`. What would that look like?
- What is an `EventHandler`? Some examples have this, but the current docs don't. I see from the changelog that it's been renamed to `Projector`, but the examples were a source of confusion until I found this.
- What does the aggregate repository do? Does `add_aggregate` write to the DB? If so, which DB and what records are made? What does an `update_aggregate` operation look like?
- There are 3 DB tables in the `sequent_schema`: `event_records`, `command_records` and `stream_records`. What are they used for and when? Events I assume are used to rebuild the aggregates, but commands I don't see mention of being used and I don't know what streams are at all.
- Initially, it was not clear to me that the `aggregate_id` needed to be manually generated. I was assuming it would be automatically made on `repository.add_aggregate`
- Why is it not possible to do a zero downtime migration to add a new projection (leaving the existing ones alone)? Is this theoretically possible in future or will it never be?
- Is it OK to rename `aggregate_id` as `id` in the projections so as to be consistent with our other services? Does this matter or not?

Hopefully that's useful. I'm not very familiar with the CQRS pattern so perhaps some of these questions arise from seeing this project as my first experience with event sourcing. I'm happy to help with writing the documentation if that would be useful, but I don't know the answers to all of the above questions yet.

_Originally posted by @mattgibson in https://github.com/zilverline/sequent/pull/121#issuecomment-421960062_

**Comment by lvonk** [comment]
Hi @mattgibson,

Some questions are indeed more CQRS and event sourcing related, so will answer those to the best of my knowledge.

> Why are AggregateRoots and Projectors different classes?

AggregateRoot's encapsulate your domain logic. Projectors provide projections on your events typically stored in tables in the view_schema. 
Indeed some Projectors handle the same events as the AggregateRoot, but you can also imagine creating specialized Projectors that for instance sum all amount of invoices per particular month. 
Another use case is specific projections that enables you to do `select * from view_schema.dashboard where user_id = '?'`. In this case you could build a `DashboardProjector` that inserts and update all data you want to show on the dashboard.

> What is an EventHandler? 

An `EventHandler` is renamed to `Projector`. I searched the docs on the master branch and I think all references to `EventHandler` have been already renamed.

> Why is it not possible to do a zero downtime?

Events come in while you replay, for now we choose to do some downtime which is easier to implement. We hope to achieve no downtime in the foreseeable future.

> Is it OK to rename aggregate_id as id

Sequent relies on the fact that is it name `aggregate_id` in several places. You can choose other names in your Projections.

**Comment by mattgibson** [comment]
Thanks @lvonk. That's really helpful!

**Comment by lvonk** [comment]
Hi @mattgibson 

I created seperate issues from your feedback. I will close this issue and continue with the individual ones.
