### ISSUE TITLE
Using commands and aggregates

### ISSUE THREAD

**Issue by sophiedeziel** [zilverline/sequent#163]
First of all, I'm sorry if this isn't the right place for the kind of questions I have. Couldn't find the official way to contact you for questions (IRC? Slack? email?). 

I successfully created an app that creates an account, based on your getting started guides. So far, I like how sequent is built and how I interact with it. I am already very familiar with ActiveRecord, so I really appreciate that it is used for the event store.

Now, I try to understand what are correct and bad ways to implement defaults and building relationships between aggregates. For example, an account can hold a lot of things. There's credential info, it can also hold identity info, contact info, licence, preferences, etc. With Rails and traditional CRUD, I could create multiple models for each one of those concepts. Then, I would use an `after_create` hook to create the associated records for the user.

Would all commands and events be created under the same account aggregate? I looks very convenient to me.

**Comment by lvonk** [comment]
Hi,

Thanks for reaching out! Yes, for now this is certainly the right place to ask.

> Now, I try to understand what are correct and bad ways to implement defaults and building relationships between aggregates.

What we have learned in the past years is to have as little dependencies as possible between Aggregate's. If they are too dependent, perhaps they are one Aggregate. In DDD an Aggregate can be seen as a collection of objects, they encapsulate a collection of business rules. Those rules really belong together. I have added another example later on.

> Would all commands and events be created under the same account aggregate? I looks very convenient to me.

**Short answer:**
yes probably. But it depends on "the requirements" of your domain.

**Longer answer:**

So let's say we are building an invoicing app. Some of the rules are: 

- before sending you need at least: customer info and a single line item
- you can only shift vat if you have a valid VAT number of the customer
- after sending it can not be changed

So one rule applies to the Invoice (customer and VAT number), but VAT is set only set a `LineItem`. If you look at a LineItem on an Invoice it has no knowledge of the customer the Invoice is send to, it typically only has amount, quantity, vat, total. So those two objects really belong together.

`Customer` on the other hand is an Aggregate on its own. It has its own identity and busniess rules. So regarding the relationships: A Customer does not need to know how many Invoices it has sent to perform any of its business rules (again, this is of course highly depends on the requirements of the app you are building), but as stated above in the example an `Invoice` must now to which `Customer` it is send. So the Invoice has a `set_customer_id`, but the Customer has no collection of Invoices, so there is no `Customer.add_invoice` in this case. However this can still be queried and displayed in the UI using projections where there is a `CustomerRecord.has_many :invoice_records`.

Hope this helps.

**Comment by sophiedeziel** [comment]
Thank you, yes it helps a lot! I really appreciate the time you spent answering my questions. I feel more confident going forward in the project.

**Comment by lvonk** [comment]
Great! If you have more questions, or feedback on the documentation please let us know so we can improve.
