### ISSUE TITLE
ActiveRecord 6

### ISSUE THREAD

**Issue by sophiedeziel** [zilverline/sequent#166]
I am trying Sequent with the beta1 version of ActiveRecord 6.0.0, in a Rails app. It seems to work just fine. Is there any roadmap to make sure Sequent is fully compatible when the official version of Rails 6.0 comes out?

Right now, I am testing with my own fork because I had to edit the gemspec to resolve Bundlers' dependencies conflicts.

**Comment by lvonk** [comment]
We typically wait until a new major version is released and then do the upgrade. We haven't had much issues in upgrading AR so far so I suspect this upgrade will be done soon after it comes out.
