### ISSUE TITLE
Add explicit assertion for payload variables

### ISSUE THREAD

**Issue by BaylorRae** [zilverline/sequent#171]
I noticed while writing specs that the sequence number wasn't being validated and I think it's related to `payload_variables` being rejected before serialization.

https://github.com/zilverline/sequent/blob/f1f966716cad6147f894b6ec5e08382ff2dfbb24/lib/sequent/core/event.rb#L23-L36

My thoughts are updating **command_handler_helpers.rb** and **event_handler_helpers.rb** to also include `aggregate_id` and `sequence_number` but want to make sure there's not a better location to add this.

```diff
diff --git a/lib/sequent/test/command_handler_helpers.rb b/lib/sequent/test/command_handler_helpers.rb
index f866793..361ff02 100644
--- a/lib/sequent/test/command_handler_helpers.rb
+++ b/lib/sequent/test/command_handler_helpers.rb
@@ -143,8 +143,17 @@ module Sequent
 
         Sequent.configuration.event_store.stored_events.zip(expected_events.flatten(1)).each_with_index do |(actual, expected), index|
           next if expected.class == Class
-          _actual = Sequent::Core::Oj.strict_load(Sequent::Core::Oj.dump(actual.payload))
-          _expected = Sequent::Core::Oj.strict_load(Sequent::Core::Oj.dump(expected.payload))
+
+          _actual = Sequent::Core::Oj.strict_load(Sequent::Core::Oj.dump(actual.payload)).merge({
+            'aggregate_id' => actual.aggregate_id
+            'sequence_number' => actual.sequence_number
+          })
+
+          _expected = Sequent::Core::Oj.strict_load(Sequent::Core::Oj.dump(expected.payload)).merge({
+            'aggregate_id' => expected.aggregate_id
+            'sequence_number' => expected.sequence_number
+          })
+
           expect(_actual).to eq(_expected), "#{index+1}th Event of type #{actual.class} not equal\nexpected: #{_expected.inspect}\n     got: #{_actual.inspect}" if expected
         end
       end
```

**Comment by lvonk** [comment]
Hi,

Yes that is done intentionally for ease of testing so you don't have to worry about Sequent passing in the right `aggregate_id` and `sequence_number` all the time. You still can of course but not with these helpers.

So I'd rather provide an extra helper something like `then_exact_events` or introduce a flag that you want this during testing: `then_events(FooEvent, exact: true)`

@stephanvd thoughts?
