### ISSUE TITLE
Getting started guide uses the wrong directory for Sinatra templates

### ISSUE THREAD

**Issue by tomharvey** [zilverline/sequent#177]
By default, sinatra will use the `app/views/` directory for templates.

In the [Getting started - building a web application](https://www.sequent.io/docs/building-a-web-application.html) you instruct the creation of an era file in `app/view/index.erb`

The correct path is used later for `app/views/authors/show.erb` and `app/views/authors/index.erb` so I assume this is a typo.

**Comment by lvonk** [comment]
Yes it is a typo. Thanks!

**Comment by lvonk** [comment]
Care to create a PR for this as well? The referenced PR is for your own forked repo.

**Comment by tomharvey** [comment]
Ah. Sure thing. Will do.

**Comment by tomharvey** [comment]
Oops  -  here is the correct PR https://github.com/zilverline/sequent/pull/178/files
