### ISSUE TITLE
Errors in Getting Started guide

### ISSUE THREAD

**Issue by tomharvey** [zilverline/sequent#179]
### Undefined route after Account creation
After configuring the DB Connection pool for sinatra in the Getting Started guide p3 we should get a "success" when creating a new account through the web form. But the post method directs to the as yet undefined route at `/authors/id/#{author_id}` after the author is created.

### Missing flash output
While we create a flash notice in the controller there is no flash being printed in the template.

### We forget to require AuthorProjector after we define it.
We create a new file in `app/projectors/author_projector.rb` but do not require it in the `blog.rb` file. So, when we go to run the migration we get and error: `NameError: uninitialized constant AuthorProjector`

### There is no definition of the author events
When we implement the projector for authors in part 3 and submit the form to create a new author we get an error:

```
Sequent::Core::EventPublisher::PublishEventError - Event Handler: AuthorProjector
Event: #<AuthorNameSet:0x00007fd4ff075db0 @aggregate_id="91cd938a-9d0b-47ef-9026-5ef03a412ef7", @sequence_number=2, @created_at=Thu, 25 Apr 2019 15:29:30 +0200>
Cause: #<ArgumentError: Empty list of attributes to change>:
```

as back in part 2 we stubbed out events for `AuthorNameSet` and `AuthorEmailSet` but we never define the attributes.

===

Sorry these are coming in piecemeal, it's just as I get some spare time to follow through the tutorial - which is excellent otherwise!

**Comment by tomharvey** [comment]
Ah - one more. When trying to add a second author using the tutorial code I end up with

```Sequent::Core::EventStore::OptimisticLockingError - Sequent::Core::EventStore::OptimisticLockingError:```

Looks like this is from the first time we define Usernames aggregate root in part 2, where we instantiate `Usernames.new({aggregate_id: id})` with a has, instead of just passing the ID value.

**Comment by lvonk** [comment]
Thanks a lot! Really appreciate the help :-)
