### ISSUE TITLE
Support patch versions for projections

### ISSUE THREAD

**Issue by lvonk** [zilverline/sequent#190]
Currently there is a single strategy of building projections:

The new projection is created in a background process by replaying all events. At the end the application needs a little downtime to get the events added after the new projection was created.

This strategy is fast and works great if the projections don't need many events (let's say less then 5.000.000) to rebuild its state. Also having a single strategy is simple and easy to understand.

During a lot of migrations we are just adding data to the new projection. Data that previously did not exist. In this case it makes no sense to rebuild the entire projection again. Although downtime is still minimized rebuilding a projection in the background can take significant amount of time. For example an event store of > 200M events and replaying ~ 15M events can take up to an hour in the background.

So what we like to have is a way of allowing new data in projections (adding columns to a table) without needing to rebuild the entire projection. This can be achieved by adding a patch version. 

Proposal to implement this:

```ruby
class ViewSchemaMigrations < Sequent::Migrations::Projectors
  def self.version
    '1.1'
  end
  def self.versions
    {
      '1' => [InvoiceProjector, EstimateProjector],
      '1.1' => [InvoiceProjector],
    }
  end
end
```

We then also need the following sql files:

`invoice.sql` containing the initial table creation.
`invoice_1.1.sql` containing the addition of the columns.

The `Sequent::Migrations::ViewSchema::Versions` needs to have an extra column `patch_version` to store the current patch version (default 0).

In `Sequent::Migrations::ViewSchema.migrate_offline` we can implement applying the patch version.

We also need to think about how to deal with rollbacks and if we want to support the following scenario: upgrading from version '1.0' via '1.1' directly to version '2.0'.

cc @stephanvd @bforma @mvandiepen

**Comment by stephanvd** [comment]
I like this solution! Nice that it's opt-in like that. One doesn't need to know about it until they're at scale and looking for an advanced topic like this.

Patches don't really need projectors. To be more explicit about what's happing in patch versions so we can point to the table to alter. i.e.:

```
  def self.versions
    {
      '1' => [InvoiceProjector, EstimateProjector],
      '1.1' => [AlterTable.new('invoice_records')],
    }
  end
```

> We also need to think about how to deal with rollbacks and if we want to support the following scenario: upgrading from version '1.0' via '1.1' directly to version '2.0'.

**Upgrading 1.0 -> 2.0:**

This should just pick up the new structure from invoice.sql which needs to be kept in sync so I don't see any issues here. Perhaps we should even validate the output if the patch to match all the columns of the invoice.sql file.

**Downgrading:** 

Patch level migrations should be simple, risk-free migrations like adding a single column or fixing up some data in a column in a way that doesn't break the currently running code.

I'd say they're irreversible. You can always type `drop column` in a console if you really regret adding it. You can of course go back a major version. i.e. I'm on version 2, patch to 2.1, roll back to version 1.

Upgrading again should be to 2.1, plain version 2 does not conceptually exist anymore and should error.

**Comment by lvonk** [comment]
> Patches don't really need projectors.
Yes you are right. we need this on a table level.

> Perhaps we should even validate the output if the patch to match all the columns of the invoice.sql file.

This means we duplicate the change? Both in `invoice_records.sql` and the `AlterTable`? I want to see if we can prevent this.

**Comment by stephanvd** [comment]
> This means we duplicate the change? Both in invoice_records.sql and the AlterTable? I want to see if we can prevent this.

I feel like the alternative to this would be an `ActiveRecord::Migration` dump to `structure.sql`/`schema.rb` and/or reimplementing the tracking of applied patches in the db. At this point why not adapt `ActiveRecord::Migration` to become "version aware" so we get up/down migrations too. The double definition seems simpler in comparison. Or am I missing a simpler solution? Replay all patches in order on every new version?

**Comment by lvonk** [comment]
> At this point why not adapt ActiveRecord::Migration to become "version aware" so we get up/down migrations too

I think with these patches we only go up and don't need a down. Also the `ActiveRecord::Migration` doesn't really fit the "major" upgrades when we rebuild an entire projector. So I am not sure if adapting `ActiveRecord::Migration` is the way to go.

> Replay all patches in order on every new version?

Yes I would say this for starters.

**Comment by lvonk** [comment]
After trying to implement I think it is simpler to just skip the patch version suffix and just go for:

```ruby
def self.versions
    {
      '1' => [InvoiceProjector, EstimateProjector],
      '2' => [AlterTable.new('invoice_records')],
    }
  end
```

We could then even support:

```ruby
def self.versions
    {
      '1' => [InvoiceProjector],
      '2' => [AlterTable.new('invoice_records'), EstimateProjector],
    }
  end
```

We could even support a `down` if people extend the AlterTable and implement `down`

```ruby
  class AddColumnToInvoiceRecords < AlterTable
    def down
      # drop colum
    end 
  end
```

**Comment by lvonk** [comment]
Added to 3.3
