### ISSUE TITLE
ValueObject to store json

### ISSUE THREAD

**Issue by lukegalea** [zilverline/sequent#191]
I'd like to pass a hash into some events and commands. 

I'm struggling to find the best way to write a custom ValueObject that serializes to json and back.

Mind pointing me in the right direction? Thanks!

**Comment by lvonk** [comment]
There is no support, yet, for defining `Hash` as type for `attrs`. We sometimes just serialize a hash as json string into an event. The 'important' attributes are specified in an event, but the rest serialized as json string.

For instance:

```ruby
class PaymentReceived < Sequent::Event
  attrs payment_id: String, 
  status: String, 
  raw_attributes: String # json

  def raw_attributes_hash
    JSON.load(raw_attributes)
  end
end

apply PaymentReceived,
  payment_id: payment_hash['payment_id'],
  status: payment_hash['status'],
  raw_attributes: payment_hash.to_json
```

Is this what you mean?

**Comment by lukegalea** [comment]
Hi @zilverline-tech (Ivonk) - I think that'll work, thanks! But, it would be great to have an easier way to write custom values (to do custom serialization/deserialization) without monkey patching Sequent.

I'm trying to implement something similar to what I had accomplished using Elixir's Commanded library and it's quite challenging in Sequent specifically because of that.

Anyway - I appreciate your help. If I find I can't make it work I may try to refactor and submit a PR ;)

**Comment by lvonk** [comment]
Maybe I understood it wrong but a class that extends `Sequent::ValueObject` are serialized and deserialized out-of-the box. So:

```ruby
class Address < Sequent::ValueObject
  attrs street: String, postal_code: String
end

class CreateAddress < Sequent::Command
  attrs address: Address
end
```

Works out-of-the-box. There is no support for `Hash` as type for `attrs` though. Does this help?
