### ISSUE TITLE
Calling load_aggregate outside of a CommandHandler leads to cache desyncs

### ISSUE THREAD

**Issue by rintaun** [zilverline/sequent#200]
Right now the unit-of-work cache is only cleared when the command service completes a unit of work. That means that if in `Thread 1` I call `load_aggregate` and then in `Thread 2` call `execute_command` for that aggregate, I will now have two different copies of the aggregate in each thread, since it is cached in `Thread 1`.

 I think the intention might be that applications should not load aggregates outside of command handlers, but whether that's true or not is not clear.

There are probably at least three approaches to addressing this issue, either:

* update the documentation to plainly describe the limitations on aggregate access
* move the unit-of-work cache out of `AggregateRepository` and into `CommandService` -- effectively, `AggregateRepository#load_aggregate` would no longer cache aggregates, but a unit-of-work cache would still be maintained with uncommitted events within command processing.
* update the cache to check whether any new events have occurred on the aggregate since it was cached, then incrementally apply any new events to the aggregates if necessary.

**Comment by lvonk** [comment]
Hi @rintaun 

> That means that if in Thread 1 I call load_aggregate and then in Thread 2 call execute_command for that aggregate, I will now have two different copies of the aggregate in each thread, since it is cached in Thread 1.

Each thread will have it's own Unit-of-Work, so if you load the same aggregate in 2 different threads each Thread has its own copy (and caches it). The doc in the `AggregateRepository` already mentions this, but it is indeed a good idea to also add this to https://www.sequent.io/docs/concepts/aggregate-repository.html:

```ruby
module Sequent
  module Core
    # Repository for aggregates.
    #
    # Implements the Unit-Of-Work and Identity-Map patterns
    # to ensure each aggregate is only loaded once per transaction
    # and that you always get the same aggregate instance back.
    #
    # On commit all aggregates associated with the Unit-Of-Work are
    # queried for uncommitted events. After persisting these events
    # the uncommitted events are cleared from the aggregate.
    #
    # The repository keeps track of the Unit-Of-Work per thread,
    # so can be shared between threads.
    class AggregateRepository
    end
  end
end
```

If you load an aggregate outside of the "transaction" started by `CommandService` then indeed you should take care of your own memory management. You need to clear the `AggregateRepository` when you are done. See `AggregateRepository#clear!` or `AggregateRepository#clear`.
