### ISSUE TITLE
`sequent:db:create_event_store` will fail for some DB username

### ISSUE THREAD

**Issue by LittleTwoCheng** [zilverline/sequent#208]
## GIVEN
the connected DB username is either:
(i) identify with any keyword defined in PG, or
(ii) a case sensitive string.
Let's assume it is a random string "Aw1PrIwW"

## WHEN

try to run the sequent migration tasks which help create schema:
`rake sequent:db:create_event_store`

## EXPECTED

it will run as expected, Schema like `sequent_schema` should be created.

## CURRENTLY

No, it will fail. rake command will be aborted by following error message:

```
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  role "aw1prIww" does not exist
: CREATE SCHEMA IF NOT EXISTS sequent_schema AUTHORIZATION Aw1PrIwW
```

## My Guess on Why

at `lib/sequent/support/database.rb` this method `self.create_schema`

The User role part of the Sql query is not double quoted, so a username 'Aw1PrIwW' will be treated as 'aw1prIww'. Then, system cannot find this user role.

**Comment by benchengggv** [comment]
https://github.com/zilverline/sequent/blob/master/lib/sequent/support/database.rb#L50
