### ISSUE TITLE
State in Workflows?

### ISSUE THREAD

**Issue by drteeth** [zilverline/sequent#209]
Hi, first of all, a big thank you for all the hard work on Sequent.

I'm wondering how you recommend handling state in workflows. By that I mean if a workflow needs to keep state to do it's work, where should that be kept? In a separate projection? In a Record but one that is managed by the workflow? A normal ActiveRecord model? Something else?

As a (contrived) motivating example:
Imagine a Workflow for calculating achievements:

```ruby
class GranterOfAchievements < Sequent::Workflow
  on ProductPurchased do |event|
    purchase_count = get_state_somehow(event.customer_id)
    new_count = purchase_count + 1
    store_state_somehow(event_customer_id, new_count)

    if new_count == 10
      command = GrantAchievement(
        aggregate_id: event.customer_id, 
        name: 'First Ten Yay'
      )
      Sequent.command_service.execute_commands(command)
    end
  end
end
```

I understand that it's better to have stateless Workflows, but it's not always possible. What is the Sequent take on this?

Thanks

**Comment by lvonk** [comment]
Hi @drteeth 

Thanks for the compliment :-).

> By that I mean if a workflow needs to keep state to do it's work, where should that be kept?

It can be all of the above. You could use:
- an Aggregate to get the state
- a projection
- a customer projection
- a non event sourced model

> What is the Sequent take on this?

There is no one best way to implement this. It highly depends on your domain and what you decide is part of your domain. So really all of your proposed solutions could work and we have implemented several of them like you propose. To make to correct decision you also need to take consistency, performance etc into account (e.g. registering millions of events in a single aggregate is not the best idea...)

So just to give my opinion and how we implemented similar workflows in the past:

1. At first sight this looks like something that is stored in your domain. If `purchase_count` is something significant in your domain, I can imagine that is tracked in for instance a `Customer` domain object. If this is the approach you could execute another command and let the Customer handle this.

```ruby
on ProductPurchased do |event|
  Sequent.command_service.execute_commands(
    RegisterPurchase.new(
      aggregate_id: event.customer_id,
      product_id: event.aggregate_id,
   )
  )
end
```

A `CustomerCommandHandler` could then handle this command:

```ruby
class CustomerCommandHandler < Sequent::CommandHandler
  on RegisterPurchase do |command|
    customer = Sequent.aggregate_repository.load_aggregate(command.aggregate_id)
    customer.register_purchase(command)
  end
end

class Customer < Sequent::AggregateRoot
  def register_purchase(command)
    apply PurchaseRegistered
    apply AchievementGranted if @purchase_count > 10
  end

  on AchievementGranted do
    @purchase_count += 1
  end
end
```

2. If this is not something you want to register in your domain I can imagine you can query a projection of purchases. This could be a projection specific for this task but also an existing projection.

```ruby
class GranterOfAchievements < Sequent::Workflow
  on ProductPurchased do |event|
    new_count = SalesRecord.where(customer_id: event.customer_id).count
    if new_count == 10
      command = GrantAchievement(
        aggregate_id: event.customer_id, 
        name: 'First Ten Yay'
      )
      Sequent.command_service.execute_commands(command)
    end
  end
end
```

Hope this helps.
