### ISSUE TITLE
Errors in Getting Started guide

### ISSUE THREAD

**Issue by yanovitchsky** [zilverline/sequent#212]
In the getting started, When trying to create an author nothing happens.
You actually forgot to register the author_command_handler in the sequent initializer.

```Sequent.configure do |config|
  config.migrations_class_name = 'Migrations'

  config.command_handlers = [
    PostCommandHandler.new,
    AuthorCommandHandler.new,
  ]

  config.event_handlers = [
    PostProjector.new
  ]
end
```

**Comment by lvonk** [comment]
Which part of the getting started are you referring to? It is mentioned in [Building a web application with Sequent Guide](https://www.sequent.io/docs/building-a-web-application.html)

**Comment by yanovitchsky** [comment]
The registration happens down the page in section 4
```
require './db/migrations'

Sequent.configure do |config|
  config.migrations_class_name = 'Migrations'

  config.command_handlers = [
    PostCommandHandler,
    AuthorCommandHandler,
  ].map(&:new)

  config.event_handlers = [
    PostProjector,
    AuthorProjector
  ].map(&:new)
end
```
If you go to the section ```Let’s inspect the sequence_schema and see if the events are actually stored in the database.```
Nothing happens, there are no events because the handler is not registered yet.

**Comment by lvonk** [comment]
Ah yes, I see now. Yes that is indeed missing. Thanks for reporting
