### ISSUE TITLE
Tests will not run with Postgres 12

### ISSUE THREAD

**Issue by mattgibson** [zilverline/sequent#216]
This is really a heads-up in case anyone else hits the same issue and thinks it's a problem with Sequent. 

Reproduction:
1. Install Postgres 12 so it's the system default
2. Clone this repo and install gems (I tested with Ruby 2.6.5)
3. Follow the setup instructions for running the specs
4. Run the specs via `bundle exec rake spec`

You'll see a segfault from the pg gem.

Upstream issue is here: https://github.com/ged/ruby-pg/issues/311

Workaround: 
```
PGGSSENCMODE="disable" bundle exec rake spec
```

**Comment by lvonk** [comment]
Thanks for pointing this out! I will pin this issue for now.

**Comment by lvonk** [comment]
@mattgibson is still the case?

**Comment by mattgibson** [comment]
With th latest Postreges 12 installed via Postgres.app, this seems to be OK now. I can't work out what's changed, but I suspect the pg gem.
