### ISSUE TITLE
Seemingly Incorrect active_star_version (activerecord, activemodel, activesupport)

### ISSUE THREAD

**Issue by nbibler** [zilverline/sequent#227]
The gemspec currently defines an "active_star_version" as:

https://github.com/zilverline/sequent/blob/d48a8bca6e31adee4d1059a37fcea382c90ed551/sequent.gemspec#L24

I'm assuming this is not intended as it doesn't make much sense. Either:

* You want 5.x but don't want Rails 6 support at all, which would be `['>= 5', '< 6']`, or
* You want 5.x and 6.0.x which would be `['>= 5', '< 6.1']`, or
* You want all of 5.x and all of 6.x which would be `['>= 5', '< 7']`.

Locking to `['>= 5.0', '<= 6.0']` means it allows all of 5.x but only strictly `6.0.0` from the 6.x releases. That means it uses activerecord 6.0.0, but not 6.0.2. I assume this is not what was intended.

As of this issue being created, [activemodel 6.0.2.1](https://rubygems.org/gems/activemodel/versions/6.0.2.1) is the current release, but cannot be used.

**Comment by lvonk** [comment]
`< 6.1` is indeed what was intended. Good catch.
