### ISSUE TITLE
Database config and schemas/migrations must be kept in the same folder

### ISSUE THREAD

**Issue by mattgibson** [zilverline/sequent#245]
When integrating Sequent in Rails, it would be more intuitive to keep the migration and schema files in `/db` or in a subfolder like `/db/sequent`, as all similar Rails files are. This is currently not possible because `database_config_directory` controls the location of both, leaving no option but to have them in `/config` along with the rails `database.yml` file.

https://github.com/zilverline/sequent/pull/244 provides a fix by introducing a new configuration parameter `database_schema_directory` for the location of the schema files, which defaults to the same location as `database_config_directory`.

**Comment by lvonk** [comment]
Fix merged.
