### ISSUE TITLE
Add Ruby 3 / Rails 6 support

### ISSUE THREAD

**Issue by JulienItard** [zilverline/sequent#251]
Hello, just want to know if it's planned to add support for ruby 3 and rails 6 ? thanks :)

**Comment by lvonk** [comment]
Hi,

Yes this is definitely something we are going to support. Rails 6 is already supported btw. We don't know a precise date yet though.

**Comment by lvonk** [comment]
Hi @JulienItard you can already take a look at https://github.com/zilverline/sequent/pull/252. We are going to do some extensive testing with our own apps to make sure it works. After that we will merge and release a new version of the gem.

**Comment by lvonk** [comment]
Sequent 4.0 supports Ruby 3.
