### ISSUE TITLE
Question: data source adapters?

### ISSUE THREAD

**Issue by estevaoam** [zilverline/sequent#254]
Hi all! 

I've just run across this library and firstly: thanks for all your work on it. 

Secondly, I was wondering if an adapter-based DB connections is on your roadmap. It would be very nice to be able to use it with other technologies like Kafka instead of just supporting Postgres.

Thanks! :)

**Comment by lvonk** [comment]
Hi @estevaoam, 

No sorry, we do not have that on the roadmap currently.
