### ISSUE TITLE
Rails 6 issue with run sequent rake tasks

### ISSUE THREAD

**Issue by valexl** [zilverline/sequent#259]
Hey. I experienced with issue when I tried to run `sequent:db:create_event_store` on rails 6:

`Errno::ENOENT: No such file or directory @ rb_sysopen - db/database.yml`

at the same time when move `database.yml` from `db` to `config` folder then rails complains on ` bundle exec rake db:setup`:

`Could not load database configuration. No such file - ["config/database.yml"]`

**Comment by lvonk** [comment]
You should be able to set `database_config_directory` in your sequent initializer: 
See https://github.com/zilverline/sequent-examples/blob/master/rails-blog/config/initializers/sequent.rb

I also now see that the documentation has an error: https://www.sequent.io/docs/rails-sequent.html (the `database_config_directory` is set twice). I will fix the documentation.

**Comment by eimantas** [comment]
I think this issue can be closed now.

**Comment by nmacuk** [comment]
bump, even though my initializer looks like this

``` ruby
require_relative "application_error"

require_relative "../migrations"

Rails.application.reloader.to_prepare do
  Sequent.configure do |config|
    config.migrations_class_name = "Migrations"
    
    # event and command handlers ommited

    config.database_config_directory = "config"
    config.migration_sql_files_directory = "db/tables"
  end
end
```

I still get the same error when trying to run `bin/rails sequent:create_event_store` task.

What's interesting, I have put some debuggers inside sequent source code and it indeed does not see the updated database_config_directory` variable/

What's even more interesting, if I run this command from inside a `.rake` file like this `Rake::Task["sequent:create_event_store"].invoke` it works and reads the config correctly.

Any thoughts?

**Comment by lvonk** [comment]
Hi, which sequent / rails version are you on? We made a lot of improvements on the Rails integration last weeks but they are all on the `master` branch.

Also, what I noticed, but haven't figured out completely is that the `rails` command somehow behaves differently from `rake`. So can you try `rake sequent:create_event_store`?

**Comment by nmacuk** [comment]
Hi,
Sequent version: 5.0 -> in gemfile we have this
`gem "sequent", git: "https://github.com/zilverline/sequent"`
the `Gemfile.lock` says 

```
sequent
  remote: https://github.com/zilverline/sequent
    sequent (5.0.0)
```
and `rails 7.0.4` with `ruby 3.2.0`

sadly after trying with `bin/rake` or `rake` I still get the same error

**Comment by lvonk** [comment]
Can you upgrade to current master and try?
