### ISSUE TITLE
`type_cast` is deprecated in activerecord 6.1.x

### ISSUE THREAD

**Issue by stephanvd** [zilverline/sequent#263]
It seems like the way we cast types for the `ReplayOptimizedPostgresPersistor` is not reliable:

```
The type information for type casting is entirely separated to type
object, so if anyone does passing a column to `type_cast` in Rails 6,
they are likely doing something wrong. See the comment for more details:
```

From: https://github.com/rails/rails/commit/92360e9ea3674c153adf2fa4c2cdcb6d9afd730b

Related: https://github.com/rails/rails/blob/28d815b89487ce4001a3f6f0ab684e6f9c017ed0/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L33-L42

**Comment by lvonk** [comment]
> The column does not have sufficient type information if the user
> provided a custom type on the class level either explicitly (via
> Attributes::ClassMethods#attribute) or implicitly (via
> AttributeMethods::Serialization::ClassMethods#serialize, +time_zone_aware_attributes+)

This is not really relevant for Sequent, but understand that this is deprecated. Any suggestions how to migrate this?

**Comment by lvonk** [comment]
Okay, perhaps there is a a higher level `type_cast_from_column` available which takes these possible custom types into account?

**Comment by stephanvd** [comment]
Just discussed this and the `active_record_persistor` solves this nicely with `Arel`. See `#convert_to_values` in `lib/sequent/core/persistors/active_record_persistor.rb`

**Comment by lvonk** [comment]
@stephanvd I think you resolved this right?

**Comment by lvonk** [comment]
This is resolved by using `type_cast` without a column value. See a7f2a98bf23bff3bfced128898e7f94395c2c218
