### ISSUE TITLE
handles_message? is not matching the given class

### ISSUE THREAD

**Issue by haoxilu** [zilverline/sequent#278]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/7600503/134097482-7a576a22-3eeb-4b30-a709-7247a5da640d.png">

<img width="851" alt="image" src="https://user-images.githubusercontent.com/7600503/134097466-2fd3cbc9-4a91-4160-ab91-366b2a8c72de.png">

**Comment by lvonk** [comment]
Not sure why this happens for you, perhaps byebug is reloading class definitions. This is not a bug in sequent as far as i can tell.
