### ISSUE TITLE
Conflicting ruby versions when building from guideline.

### ISSUE THREAD

**Issue by berkes** [zilverline/sequent#288]
When following along with the [Getting Started](https://www.sequent.io/docs/getting-started.html) I ran into a minor problem:

The command `gem install sequent` picks latest stable release, so the templates come from that. These templates still have `ruby 2.6.5` as requirement [in the Gemfile](https://github.com/zilverline/sequent/commit/f383222bfb269444bf1c8dc1c7fdcc526a82a4d8#diff-b23a0cd53b4d06c5c0dcbff37d3ab85ede55b38070e568c2c986aaeab11c967eL2). Yet the Getting Started has as requirement 3.0.0.

I'm not aware of an easy way to `gem install` from a git repo. So getting the latest that matches the sequent docs, seems not possible this way. The gemfile which is then installed, however, points to the git repo, and will fetch the latest sequent. 
So when I ensure the local version to be `2.6.5` the bundle-install will fail. A fix is to manually turn the 2.6.5 in the Gemfile to 3.0.0.

Maybe it's merely a documentation issue, where there is a per-version doc?

**Comment by lvonk** [comment]
Hi, yes we need to release a new version. This is fixed (https://github.com/zilverline/sequent/pull/273) in the current master but not yet released
