### ISSUE TITLE
Is there a way to load events in batches and eventually generate snapshots?

### ISSUE THREAD

**Issue by crypto-richardli** [zilverline/sequent#303]
I have an AggregateRoot in my app with over 1.2 million events, regeneration becomes impossible after deleting all snapshots. Because `sequent` loads all events into memory at once, is there a way to load events in batches and eventually generate snapshots?

**Comment by lvonk** [comment]
Currently no, we would have to look at EventStore.load_events_for_aggregates which is currently optimized for aggregates of "normal" size.

Perhaps we could introduce a new `load_events_for_aggregate_snapshotting` which uses `find_each`  to keep memory consumption low, although with so many events I still wonder if the snapshot is ready in an acceptable time.

Generally I would advice against a single aggregate having so many events. Could you share your use case? Perhaps you can consider splitting this up in (a lot of) smaller aggregates? Or even consider not event sourcing this particular concern?

**Comment by lvonk** [comment]
Hi @crypto-richardli this is now implemented via https://github.com/zilverline/sequent/pull/311
