### ISSUE TITLE
How to correctly define joined table migrations

### ISSUE THREAD

**Issue by nmacuk** [zilverline/sequent#332]
Hello!
At first I want to say that I have been testing out Sequent for a week now and I really like this framework. Great job guys! I hope it will stay maintained and maybe even I will be able to contribute after some time 😄 

However, I have a question regarding migrations:

I have three projectors with corresponding `manages_table`:
`CourseProjector (course_records, course_lesson_record)`
`UserProjector (user_records)`
`CourseProgressProjector (course_progress_records)`

`course_progress_records` is a joined table between `course_records` and `users_records`.
it’s migration file:
```sql
CREATE TABLE course_progress_records%SUFFIX% (
    id serial NOT NULL,
    uuid uuid NOT NULL,
    course_uuid uuid NOT NULL REFERENCES course_records%SUFFIX%(uuid) ON DELETE CASCADE,
    user_uuid uuid NOT NULL REFERENCES user_records%SUFFIX%(uuid) ON DELETE CASCADE,
    lessons_progresses jsonb,
    overall_progress integer,
    CONSTRAINT course_progress_records_pkey%SUFFIX% PRIMARY KEY (id)
);
CREATE UNIQUE INDEX course_progress_keys%SUFFIX% ON course_progress_records%SUFFIX% USING btree (uuid);
CREATE UNIQUE INDEX course_progress_records_course_uuid_user_uuid_index%SUFFIX% ON course_progress_records%SUFFIX% USING btree (course_uuid, user_uuid);
```
I think that in current implementation, when I want to migrate and upgrade to a new version and I want only to rebuild
`CourseProgressProjector`, not all projectors, it does not work, because it looks for `course_records%SUFFIX%` and `user_records%SUFFIX%` which are not present with a new version suffix.

How to handle joined tables and it’s migrations correctly?

**Comment by lvonk** [comment]
Hi, thanks for reaching out. We don't support join tables. From sequent's perspective it is the responsibility of the domain (your aggregates) to enforce referential integrity. Therefor enforcing it in the projections is not needed. 

We thought about supporting it but we chose not to because:
- it makes replaying projections from events so much harder and creates constraints in which order aggregates should be replayed (Sequent replays it per aggregate).
- It doesn't add real value since the referential integrity should be enforced by the domain anyway

**Comment by nmacuk** [comment]
Thanks for clarifying. 
This makes perfect sense, I was probably just thinking in non DDD way, have to switch 😛 

Closing then. Thanks once again.

**Comment by coalest** [comment]
I have question related to this statement:

> We don't support join tables. From Sequent's perspective it is the responsibility of the domain (your aggregates) to enforce referential integrity. Therefor enforcing it in the projections is not needed.

I understand that the database validations from read tables shouldn't be needed to enforce referential integrity. But what do you mean when you say that Sequent doesn't support join tables?

Do you mean many-to-many relationships are usually mapped to join tables (via projectors) but without foreign keys? Or is that projectors normally follow more of a NoSQL/document-oriented approach where the read tables are denormalized and might include arrays/jsons to map a many-to-many relationship.

**Comment by lvonk** [comment]
I meant you can't use foreign keys ( or better: any validation in your projector is discouraged ) so yes many-to-many are usually mapped with join tables but without foreign keys.
