### ISSUE TITLE
Information request - Sequent usage

### ISSUE THREAD

**Issue by lvonk** [zilverline/sequent#346]
Hi all,

Since our main app is growing steadily we are currently starting to implement a version of the event store to better accommodate for serious scale using Postgres database sharding. This made us wonder who else is using Sequent in production and on what scale? If you are willing to share by filling in this short google form:

https://forms.gle/5aosUfQPAutZxtn57

**Comment by lvonk** [comment]
Application: www.jortt.nl
Number of events: ~ 930.000.000 (20/30M added each month)
Webframework: Sinatra, Grape

**Comment by lvonk** [comment]
Application: secret, not launched yet
Number of events: 0
Webframework: Rails

**Comment by coalest** [comment]
The app we're working on isn't yet live, so I have yet to fill out the form. But I am curious about the information gathered. Will you share any anonymized results from this survey?

**Comment by lvonk** [comment]
Hi, I want to gather some more feedback first. We can share some basic anonymized feedback I guess. The biggest event store up until now is still our own app (running in production over 10 years now), size is ~ 900GB with > 1.000.000.000 events in it.
