### ISSUE TITLE
FakeEventStore should raise a non unique error

### ISSUE THREAD

**Issue by s0meone** [zilverline/sequent#36]
The event records table in the actual event store raises a duplicate key error for the aggregate id, but the `FakeEventStore` does not.

**Comment by lvonk** [comment]
Hi @s0meone, better late than never... 🙈 

The `event_records` table actually raises an error if the `aggregate_id` and `sequence_number` combination is duplicate. 
The `FakeEventStore` has always been lenient about this being duplicate for easy testing purposes, meaning uses the order of the events as sequence. 
Changing this will probably break a lot of users so I am thinking of creating another `FakeEventStore` that will implement this behaviour.

Thoughts?

**Comment by s0meone** [comment]
If this change breaks your test suite, it probably is already broken, isn't it?

You could implement a warning and add an option to the `FakeEventStore` that will change the warning to an error (sort of a `strict` mode)?

**Comment by lvonk** [comment]
> If this change breaks your test suite, it probably is already broken, isn't it?

Not really i think. The case is this:

```ruby
it 'is the first text case' do
  given_events foo_event, bar_event, foobar_event
end

it 'is the second test case' do
  given_events foo_event, foobar_event
end
```

versus:

```ruby
it 'is the first text case' do
  given_events foo_event.copy(sequence_number: 1), 
    bar_event.copy(sequence_number: 2), 
    foobar_event.copy(sequence_number: 3)
  when_command BarFooCommand
end

it 'is the second test case' do
  given_events foo_event.copy(sequence_number: 1),
    foobar_event.copy(sequence_number: 2)
  when_command BarFooCommand
end
```

This makes the tests less readable and cumbersome to create, in the first test case `foobar_event` needs `sequence_number` 3 and the last test case `sequence_number` 2. 

So we can add a `strict` mode but the consequence will be that ☝️

**Comment by s0meone** [comment]
Not entirely correct because sequence numbers may have gaps, but I get your point. You'll need to keep track indeed.

But that's where `given_stream_for` comes in? I believe the test events should represent real world events as close as possible, including sequence numbers.

**Comment by lvonk** [comment]
Autoclosing this issue...
