### ISSUE TITLE
Old versions on projections are kept after migration?

### ISSUE THREAD

**Issue by bforma** [zilverline/sequent#364]
After I ran a migration (`bundle exec rake sequent:migrate:online` and `bundle exec rake sequent:migrate:offline`) I noticed that the old version of a projection table is still in the schema. Is that intentional? Should we clean those up ourselves regularly?

**Comment by lvonk** [comment]
Yes that is intentional for disaster recovery purpose. The old tables will be deleted on the next migration, meaning Sequent only keeps the previous version. You could of course delete those yourself if you don't want that.
