### ISSUE TITLE
Rails migration clashing

### ISSUE THREAD

**Issue by coalest** [zilverline/sequent#367]
Hello again! 👋 

We have a use case where it would be helpful to create Postgres views that reference some of our read tables in the `FROM` clause. The [scenic](https://github.com/scenic-views/scenic) gem allows you to create Rails migrations that create and manage these database views. But referencing the read tables in Rails migrations is causing problems.

Let's say we want to create a `db/views/user_records_v01.sql` view just as a simple example:
```sql
SELECT uuid, email, username, full_name
FROM student_records
UNION
SELECT uuid, email, username, full_name
FROM admin_records;
```

If we run the Rails migration that creates that view before we have built our Sequent `view_schema`, then we would get an error such as this:
```
== 20230208192715 CreateUserRecords: migrating ====================
-- create_view(:user_records)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "student_records" does not exist
```
 
If we run the Rails migration after those tables are created, then everything works as expected. But even so, I believe the view would break if we created new versions of those read tables (`student_records_2` for example).

One possible solution would be to run our Rails migrations in two steps. First, those that need to be run before we create the `view_schema` (for example we have some migrations that create enums that are referenced in our read table schemas). And then, in a second Rails migration, create Postgres views after our `view_schema` has been created. Although one problem there is that rolling back migrations could be quite messy.

Is there perhaps a better way to create views, maybe the Sequent way?

**Comment by lvonk** [comment]
Hi,

I assume that when you say read table you are referring to the tables managed by Sequent's Projectors (aka Projections)? 

> But even so, I believe the view would break if we created new versions of those read tables (student_records_2 for example).

No this is not the case. The new version of the Projection will still be called `student_records`. Only while running a sequent migration a temporary `student_records_2` is created and filled during `sequent:migrate:online`. 
When running `sequent:migrate:offline`, to finish up Sequent's migration, the existing `student_records` is renamed to `student_records_1` and `student_records_2` is renamed to `student_records`. So this should not break the view imo.

Does this help?
