### ISSUE TITLE
Question About Major Changes and Migrations in Sequent

### ISSUE THREAD

**Issue by eduscrakozabrus** [zilverline/sequent#436]
Thank you for your work on Sequent — it’s an incredibly useful tool for working with Event Sourcing.

I recently updated Sequent to the latest version from the GitHub repository, and it broke some parts of my project. For example, I noticed that certain functions and procedures in the database stopped working, and the table structures appear to have changed.

This isn’t a big issue for me at the moment since I’m working on a development project. However, I’d like to know if there’s a centralized way to track major changes in the project — such as migrations, schema updates, and the removal of old functions and procedures.

Do you maintain a specific location (release notes, documentation, changelog) where such updates are announced? It would be helpful to understand the best practices for keeping my project aligned with new updates.

Looking forward to your advice, and thank you again for your efforts on Sequent!

**Comment by lvonk** [comment]
Hi, yes we have a https://github.com/zilverline/sequent/blob/master/CHANGELOG.md and an upgrade guide: https://sequent.io/docs/upgrade-guide.html (specifically for sequent 8).
