### ISSUE TITLE
Rails 5.0, 5.1

### ISSUE THREAD

**Issue by andriytyurnikov** [zilverline/sequent#85]
Any plans to support new rails ?

**Comment by lvonk** [comment]
Hi,

Yes I will look into this tomorrow. I will keep you updated

**Comment by bforma** [comment]
We've just released a new version of the sequent gem, which now supports Rails 4.x, Rails 5.0 and Rails 5.1.

See #87 and #88.

Also see https://rubygems.org/gems/sequent/versions/1.0.0
